### ISSUE TITLE
update KDE runtime to 5.15

### ISSUE THREAD

**Issue by eszlari** [flathub/net.jammr.jammr#1]

**Comment by stefanha** [comment]
@eszlari Is there a deprecation schedule when 5.14 will no longer be available?

**Comment by eszlari** [comment]
I don't know, you will have to ask here: https://invent.kde.org/packaging/flatpak-kde-runtime

But the freedesktop runtime 19.08 (which the KDE runtime 5.14 is based on, and which provides Mesa updates) will be EOL when version 21.08 is released (September 2021).
